---
title: "datascience_2_midterm"
output:
  html_document: default
date: "2025-03-27"
---
```{r loading libraries}
library(dplyr)
library(tidyverse)
library(survival)
library(ggsurvfit)
library(gtsummary)
library(glue)
library(labelled)
library(rpart.plot)
library(rpart)
library(party)
library(partykit)
library(caret)
```

```{r loading data sets}
load("dat1.RData")
load("dat2.RData")
```

```{r adding labels}
#mutating factor variables and creating labels for baseline characteristic table
table_data = dat1 |>
  mutate(gender = factor(gender, levels = c(0,1), labels = c("Female","Male")),
         race = factor(race, levels = c(1,2,3,4), labels = c("White","Asian","Black","Hispanic")),
         smoking = factor(smoking, levels = c(0,1,2), labels = c("Never smoked", "Former smoker", "Current smoker")),
         diabetes = factor(diabetes, levels = c(0,1), labels = c("No","Yes")),
         hypertension = factor(hypertension, levels = c(0,1), labels = c("No", "Yes")))

#creating table labels
var_label(table_data) = list(
  age = "Age (in years)",
  gender = "Gender",
  race = "Race/ethnicity",
  smoking = "Smoking status",
  height = "Height (in centimeters)",
  weight = "Weight (in kilograms)",
  bmi = "BMI (body mass index)",
  diabetes = "Diabetes",
  hypertension = "Hypertension",
  SBP = "Systolic Blood Pressure (mmHg)",
  LDL = "LDL Cholesterol (mg/dL)",
  time = "Time since vaccination (in days)"
)
```

```{r baseline characteristic table}
#outputting table
table = table_data |>
  select(age, gender, race, smoking, height, weight, bmi, diabetes, hypertension, SBP, LDL, time) |>
  tbl_summary(
    missing_text = "(Missing)",
    statistic = list(all_continuous() ~ "{median} ± {sd}")
  ) 

print(table)
```

```{r data visualization of association between predictors and log antibody levels}
##Distribution of Log Antibody Levels by Race/Ethnicity
age_antibody <- ggplot(table_data, aes(x = age, y = log_antibody)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(x = "Age", y = "Average Log Antibody Level", 
       title = "Average Log Antibody Levels by Age") +
  theme_minimal()

age_antibody

#Average Log Antibody Levels by Gender"
gender_antibody <- ggplot(table_data, aes(x = factor(gender), y = log_antibody)) +
  geom_boxplot() +
  labs(x = "Gender", y = "Log Antibody Level") +
  theme_minimal() 

gender_antibody

#Distribution of Log Antibody Levels by Race/Ethnicity
race_antibody <- ggplot(table_data, aes(x = log_antibody, fill = factor(race))) +
  geom_histogram(binwidth = 0.1, position = "identity", alpha = 0.6, color = "black") +
  labs(x = "Log Antibody Level", y = "Count", title = "Distribution of Log Antibody Levels by Race/Ethnicity") +
  scale_fill_manual(values = c("blue", "orange", "green", "purple"), 
                    labels = c("1" = "White", "2" = "Asian", "3" = "Black", "4" = "Hispanic")) +
  theme_minimal() +
  theme(legend.title = element_blank())

race_antibody

#Average Log Antibody Levels by Smoking Status
smoking_antibody <- ggplot(table_data, aes(x = factor(smoking), y = log_antibody)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(x = "Smoking Status", y = "Average Log Antibody Level", 
       title = "Average Log Antibody Levels by Smoking Status") +
  scale_x_discrete(labels = c("0" = "Never Smoked", 
                               "1" = "Former Smoker", 
                               "2" = "Current Smoker")) +
  theme_minimal()

smoking_antibody

#Distribution of Log Antibody Levels by BMI 
bmi_antibody <- ggplot(table_data, aes_string(x = "bmi", y = "log_antibody")) +
  geom_point(color = "darkgreen", alpha = 0.5) +
  geom_smooth(method = "loess", span = 0.5, color = "red", se = FALSE) +
  theme_bw() +
  labs(x = "BMI", y = "Log Antibody Levels")

bmi_antibody

#Average Log Antibody levels by diabetes status
diabetes_antibody <- ggplot(table_data, aes(x = factor(diabetes), y = log_antibody)) +
  geom_boxplot() +
  labs(x = "Diabetes", y = "Log Antibody Level") +
  theme_minimal()

diabetes_antibody

#Average Log Antibody levels by hypertension status
hypertension_antibody <- ggplot(table_data, aes(x = factor(hypertension), y = log_antibody)) +
  geom_boxplot() +
  labs(x = "Hypertension", y = "Log Antibody Level") +
  theme_minimal()

hypertension_antibody

#Distribution of Log Antibody Levels by SBP 
sbp_antibody <- ggplot(table_data, aes_string(x = "SBP", y = "log_antibody")) +
  geom_point(color = "darkgreen", alpha = 0.5) +
  geom_smooth(method = "loess", span = 0.5, color = "red", se = FALSE) +
  theme_bw() +
  labs(x = "SBP", y = "Log Antibody Levels")

sbp_antibody 

#Distribution of Log Antibody Levels by LDL
LDL_antibody <- ggplot(table_data, aes_string(x = "LDL", y = "log_antibody")) +
  geom_point(color = "darkgreen", alpha = 0.5) +
  geom_smooth(method = "loess", span = 0.5, color = "red", se = FALSE) +
  theme_bw() +
  labs(x = "LDL", y = "Log Antibody Levels")

LDL_antibody

#Distribution of Log Antibody Levels by Time Since Vaccination 
time_antibody <- ggplot(table_data, aes_string(x = "time", y = "log_antibody")) +
  geom_point(color = "darkgreen", alpha = 0.5) +
  geom_smooth(method = "loess", span = 0.5, color = "red", se = FALSE) +
  theme_bw() +
  labs(x = "Time Since Vaccination", y = "Log Antibody Levels")

time_antibody
```

```{r Bivariate analysis}
#age & antibody (p <2e-16 for intercept and age)
b <- lm(log_antibody ~ age, data = table_data)
summary(b) 

#gender & antibody (t = 17.523, df = 4972.7, p-value < 2.2e-16)
t.test(log_antibody ~ gender, data = table_data)

#race & antibody (Pr(>F) = 0.367)
anova_race <- aov(log_antibody ~ race, data = table_data)
summary(anova_race)

#smoking & antibody (Pr(>F) = 1.95e-10)
anova_smoke <- aov(log_antibody ~ smoking, data = table_data)
summary(anova_smoke)

# bmi & antibody (p-value: < 2.2e-16)
bmi_linear <- lm(log_antibody ~ bmi, data = table_data)
summary(bmi_linear) 

#diabetes & antibody p-value = 0.6828
t.test(log_antibody ~ diabetes, data = table_data)

#hypertension & antibody p-value = 5.491e-05
t.test(log_antibody ~ hypertension, data = table_data) 

#sbp and antibody p-value: 1.451e-05
sbp_linear <- lm(log_antibody ~ SBP, data = table_data)
summary(sbp_linear)  

#LDL and antibody p-value: 0.01143
LDL_linear <- lm(log_antibody ~ LDL, data = table_data)
summary(LDL_linear)

#time and antibody p-value: 0.3278
time_linear <- lm(log_antibody ~ time, data = table_data)
summary(time_linear)
```

```{r setting up data and cv}
x <- model.matrix(log_antibody ~ ., dat1) [, -1]
y <- dat1$log_antibody

x2 <- model.matrix(log_antibody ~ ., dat2) [, -1]
y2 <- dat2$log_antibody

#cross-validation
ctrl1 = trainControl(method = "repeatedcv",
                     number = 10,
                     repeats = 5,
                     selectionFunction = "best")
```

```{r gam and mars}
#GAM 
set.seed(2)
gam.fit <- train(x, y,
method = "gam",
trControl = ctrl1)

gam.fit$bestTune
gam.fit$finalModel
gam.m1 <- gam(log_antibody ~ time + age + gender + race + smoking + bmi + diabetes + hypertension + 
    SBP + LDL, data = dat1) 

gam.m2 <- gam(log_antibody ~ s(time) + age + gender + race + smoking + bmi + diabetes + hypertension + 
    SBP + LDL, data = dat1) 

anova(gam.m1, gam.m2, test = "F")

plot(gam.m2)
#Summary of the model
summary(gam.fit)

#MARS
set.seed(2)
mars_grid <- expand.grid(degree = 1:3,
                         nprune = 2:24) 

mars.fit <- train(x, y,
                  method = "earth",
                  tuneGrid = mars_grid,
                  trControl = ctrl1)
```

```{r pcr, pls, and enet}
#pcr using caret
set.seed(2)

pcr_fit = train(x,y,
                method = "pcr",
                tuneGrid = data.frame(ncomp=1:5),
                trControl = ctrl1,
                preProcess = c("center","scale"))

#pls using caret
pls_fit = train(x,y,
                method="pls",
                tunegrid = data.frame(ncomp=1:5),
                trControl = ctrl1,
                preProcess = c("center","scale"))

#enet using caret
enet_fit = train(log_antibody ~.,
                 data = dat1,
                 method = "glmnet",
                 tuneGrid = expand.grid(alpha=seq(0,1, length = 21),
                                        lambda = exp(seq(6,0,length = 100))),
                 trControl = ctrl1)
```

```{r lasso, lm, and ridge}
#lasso using caret
set.seed(2)
lasso.fit = train(log_antibody ~.,
                  data = dat1,
                  method = "glmnet",
                  tuneGrid = expand.grid(alpha=1,
                                         lambda = exp(seq(6,0,length=100))),
                  trControl = ctrl1)

#lm using caret
lm.fit = train(log_antibody ~.,
               data = dat1,
               method = "lm",
               trControl = ctrl1)

#ridge using caret
ridge.fit = train(log_antibody ~.,
                  data = dat1,
                  method = "glmnet",
                  tuneGrid = expand.grid(alpha=1,
                                         lambda = exp(seq(6,0,length=100))),
                  trControl = ctrl1)

#comparing models based on resampling results
resamp = resamples(list(lasso = lasso.fit,
                        lm = lm.fit,
                        ridge = ridge.fit))
bwplot(resamp, metric = "RMSE")

```

```{r resampling and comparing models}
#comparing models based on resampling results
resamp = resamples(list(pcr = pcr_fit,
                        pls = pls_fit,
                        enet = enet_fit,
                        gam = gam.fit,
                        mars = mars.fit,
                        lasso = lasso.fit,
                        lm = lm.fit,
                        ridge = ridge.fit))
bwplot(resamp, metric = "RMSE")
```
Based on the resampling results, the MARS model is the "best" fit as it has the lowest RMSE. 

```{r}
#creating a piece wise linear model using multivairiate adaptive regression splines (MARS)
ggplot(mars.fit)

mars.fit$bestTune
coef(mars.fit$finalModel)

#understanding the relationship between the coefficients from the final model and lpsa
p1 = pdp::partial(mars.fit, pred.var =c("time"), grid.resolution=10) |> autoplot()
p2 = pdp::partial(mars.fit, pred.var =c("smoking2"), grid.resolution=10) |> autoplot()
p3 = pdp::partial(mars.fit, pred.var =c("gender"), grid.resolution=10) |> autoplot()

p4 = pdp::partial(mars.fit, pred.var = c("age","bmi"), grid.resolution = 10) |>
  pdp::plotPartial(levelplot = FALSE, zlab="yhat", drape=TRUE, screen = list(z=20, x=-60))

gridExtra::grid.arrange(p1, p2, p3, p4, ncol=2, nrow=2)

#evaluating final model
predy2_mars2 = predict(mars.fit, newdata=x2)
mean((y2 - predy2_mars2)^2)
```
The MSE for the final model when using the test data is  0.2838458.
